# Generated by Django 4.1.2 on 2023-01-17 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_ticketmodel_to'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdvertModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='advert')),
                ('desc', models.TextField(blank=True, null=True, verbose_name=300)),
                ('url', models.URLField()),
            ],
        ),
        migrations.AlterField(
            model_name='ticketmodel',
            name='to',
            field=models.CharField(choices=[('bosaso to garowe', 'bosaaso to gaowe'), ('non', 'non'), ('bosaso to galkacyo', 'bosaso to galkacyo'), ('bosaso to qardho', 'bosaaso to qardho'), ('bosaso to lascano', 'bosaso to lascano')], default='non', max_length=255, verbose_name='toto'),
        ),
    ]
