# Generated by Django 4.1.2 on 2023-01-18 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_advertmodel_image_alter_ticketmodel_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketmodel',
            name='to',
            field=models.CharField(choices=[('bosaso to qardho', 'bosaaso to qardho'), ('bosaso to lascano', 'bosaso to lascano'), ('non', 'non'), ('bosaso to garowe', 'bosaaso to gaowe'), ('bosaso to galkacyo', 'bosaso to galkacyo')], default='non', max_length=255, verbose_name='toto'),
        ),
    ]
