# Generated by Django 4.1.2 on 2023-01-19 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_ticketmodel_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketmodel',
            name='to',
            field=models.CharField(choices=[('bosaso to galkacyo', 'bosaso to galkacyo'), ('bosaso to garowe', 'bosaaso to gaowe'), ('bosaso to qardho', 'bosaaso to qardho'), ('bosaso to lascano', 'bosaso to lascano'), ('non', 'non')], default='non', max_length=255, verbose_name='toto'),
        ),
    ]
